### ISSUE TITLE
resnet.py, diff between loading and saving weights

### ISSUE THREAD

**Issue by petteriTeikari** [hfawaz/aaltd18#2]
I think you have one extra `/` there: https://github.com/hfawaz/aaltd18/blob/94cd0e6eaa2ea4c7c150252686868ad35c73bb78/resnet.py#L21

Now, the models are saved with different paths than they are loaded and without removing that `/`, models on my Ubuntu were not saved on subdirectories, but to the same path

![image](https://user-images.githubusercontent.com/1060514/48935632-44bec380-ef43-11e8-8139-aecd2beb6e23.png)

**Comment by hfawaz** [comment]
Hello, 

Thanks for sharing, for me it worked fine, but you are right this slash is not needed here.
