### ISSUE TITLE
Definition of warping window [DTW_PARAMS]

### ISSUE THREAD

**Issue by petteriTeikari** [hfawaz/aaltd18#3]
Hi again @hfawaz  et al.

I was wondering if you used actually the following setting for your paper, i.e. you did not warp at all if I understood the code correctly and read the paper properly?

`
DTW_PARAMS = {'w':-1} 
warping window should be given in percentage (negative means no warping window)
`

In the paper [6, [Forestier et al. 2017](https://doi.org/10.1109/ICDM.2017.106), [PDF](https://germain-forestier.info/publis/icdm2017.pdf)] cited, that was given as following for the "old-school" Windows Warping (WW) method

> The Windows Warping (WW) method discussed in [11] involves warping a randomly selected slice
> of a time series by speeding it up or down. We follow the recommendations given in [11] 
> and use warping ratios equal to either 1/2 or 2 on slices representing 10% of time series’s length

![image](https://user-images.githubusercontent.com/1060514/50324519-5b444480-051a-11e9-91cc-74ec08e2b0ea.png)

Did you test out the warping with DTW?

**Comment by hfawaz** [comment]
Hello @petteriTeikari, 

Thank you for your interest, I am sorry if the comment in the code was misleading. 

By no "warping window", we meant that the warping could be infinite (there was no boundaries). 

So to answer the question: we did allow warping - this is the only setting we have tested. 

I hope this answers your inquiry.

**Comment by petteriTeikari** [comment]
I see, thanks for the clarification @hfawaz
