### ISSUE TITLE
problem in augment.py

### ISSUE THREAD

**Issue by chenfei0328** [hfawaz/aaltd18#5]
Hi,
I found that there might be a problem in function `get_weights_average_selected` which in augment.py.

In line 57, `final_neighbors_idx = np.random.permutation(k)[:subk]` What if random indexs consist of the `idx_center` ? It might cover the `idx_center`  so that the weights vector may not include the weight of 0.5 of the `init_dba`.

Therefore I added new code after the line.
`while idx_center in topk_idx[final_neighbors_idx]:`
     `final_neighbors_idx = np.random.permutation(k)[:subk]`

What do you think?

**Comment by hfawaz** [comment]
Hi, 

Nice pointing it out, thanks for sharing! 

Glad to see people benefiting from the code as well as contributing.

**Comment by chenfei0328** [comment]
Thanks for your reply!  :)
