### ISSUE TITLE
ImportError: cannot import name 'dynamic_time_warping'

### ISSUE THREAD

**Issue by whungt** [hfawaz/aaltd18#6]
Hi there,

I've successfully installed distances/dtw/setup.py. But I still got the import error in the title when running main.py. Is there anyone got the same problem?
BTW, I'm under anaconda virtual env, not sure if this causing problem.

Thanks

**Comment by hfawaz** [comment]
Hi, 

Did you manage to run the utils/build-cython.sh ? 

Maybe try changing the permissions? 

Best

**Comment by whungt** [comment]
This works.
I just missed this operation in README.md 
Anyway, Thank you.
