### ISSUE TITLE
can it be used to generate mixture of categorical and continues data? 

### ISSUE THREAD

**Issue by Sandy4321** [hfawaz/aaltd18#7]
can it be used to generate mixture of categorical and continues data? 
	for example at time t1 we have observation: red, 2.4 , 5, 12.456 and time t2: green, 3.5, 2, 45.78; time t3: black, 5.6, 7, 23.56; t4: red, 2.1, 5, 12.6 ? 

when each dimension is correlated time series and each one can be categorical and continues data?

**Comment by hfawaz** [comment]
Hello, 

Thanks for your comment. 

But for now the current algorithm do not work on a mixture of categorical and continuous data. 

Best,
